name = input("What is your name?: ")
age = int(input("How old are you?: "))
adress = input("Where are you live?: ")
print("Hello, ", name)
print("Your age is ", age)
print("You live in ", adress)
